using IX.StandardExtensions.Efficiency;

using JetBrains.Annotations;

namespace IX.StandardExtensions.Globalization;

/// <summary>
/// Country codes.
/// </summary>
[PublicAPI]
public class CountryCodes
{
    /// <summary>
    /// A list of country records, by their ISO-3166-1 alpha-2 codes.
    /// </summary>
    public static readonly Lazy<IReadOnlyDictionary<string, CountryCode>> CountriesByAlpha2 =
        new(() => new ConcurrentDictionary<string, CountryCode>
        {
            ["AD"] = new(
                "AD",
                "AND",
                "Andorra",
                1974,
                ".ad"),
            ["AE"] = new(
                "AE",
                "ARE",
                "United Arab Emirates",
                1974,
                ".ae"),
            ["AF"] = new(
                "AF",
                "AFG",
                "Afghanistan",
                1974,
                ".af"),
            ["AG"] = new(
                "AG",
                "ATG",
                "Antigua and Barbuda",
                1974,
                ".ag"),
            ["AI"] = new(
                "AI",
                "AIA",
                "Anguilla",
                1985,
                ".ai"),
            ["AL"] = new(
                "AL",
                "ALB",
                "Albania",
                1974,
                ".al"),
            ["AM"] = new(
                "AM",
                "ARM",
                "Armenia",
                1992,
                ".am"),
            ["AO"] = new(
                "AO",
                "AGO",
                "Angola",
                1974,
                ".ao"),
            ["AQ"] = new(
                "AQ",
                "ATA",
                "Antarctica",
                1974,
                ".aq"),
            ["AR"] = new(
                "AR",
                "ARG",
                "Argentina",
                1974,
                ".ar"),
            ["AS"] = new(
                "AS",
                "ASM",
                "American Samoa",
                1974,
                ".as"),
            ["AT"] = new(
                "AT",
                "AUT",
                "Austria",
                1974,
                ".at"),
            ["AU"] = new(
                "AU",
                "AUS",
                "Australia",
                1974,
                ".au"),
            ["AW"] = new(
                "AW",
                "ABW",
                "Aruba",
                1986,
                ".aw"),
            ["AX"] = new(
                "AX",
                "",
                "Åland Islands",
                2004,
                ".ax"),
            ["AZ"] = new(
                "AZ",
                "AZE",
                "Azerbaijan",
                1992,
                ".az"),
            ["BA"] = new(
                "BA",
                "BIH",
                "Bosnia and Herzegovina",
                1992,
                ".ba"),
            ["BB"] = new(
                "BB",
                "BRB",
                "Barbados",
                1974,
                ".bb"),
            ["BD"] = new(
                "BD",
                "BGD",
                "Bangladesh",
                1974,
                ".bd"),
            ["BE"] = new(
                "BE",
                "BEL",
                "Belgium",
                1974,
                ".be"),
            ["BF"] = new(
                "BF",
                "BFA",
                "Burkina Faso",
                1984,
                ".bf"),
            ["BG"] = new(
                "BG",
                "BGR",
                "Bulgaria",
                1974,
                ".bg"),
            ["BH"] = new(
                "BH",
                "BHR",
                "Bahrain",
                1974,
                ".bh"),
            ["BI"] = new(
                "BI",
                "BDI",
                "Burundi",
                1974,
                ".bi"),
            ["BJ"] = new(
                "BJ",
                "BEN",
                "Benin",
                1977,
                ".bj"),
            ["BL"] = new(
                "BL",
                "BLM",
                "Saint Barthélemy",
                2007,
                ".bl"),
            ["BM"] = new(
                "BM",
                "BMU",
                "Bermuda",
                1974,
                ".bm"),
            ["BN"] = new(
                "BN",
                "BRN",
                "Brunei Darussalam",
                1974,
                ".bn"),
            ["BO"] = new(
                "BO",
                "BOL",
                "Bolivia (Plurinational State of)",
                1974,
                ".bo"),
            ["BQ"] = new(
                "BQ",
                "BES",
                "Bonaire, Sint Eustatius and Saba",
                2010,
                ".bq"),
            ["BR"] = new(
                "BR",
                "BRA",
                "Brazil",
                1974,
                ".br"),
            ["BS"] = new(
                "BS",
                "BHS",
                "Bahamas",
                1974,
                ".bs"),
            ["BT"] = new(
                "BT",
                "BTN",
                "Bhutan",
                1974,
                ".bt"),
            ["BV"] = new(
                "BV",
                "BVT",
                "Bouvet Island",
                1974,
                ".bv"),
            ["BW"] = new(
                "BW",
                "BWA",
                "Botswana",
                1974,
                ".bw"),
            ["BY"] = new(
                "BY",
                "BLR",
                "Belarus",
                1974,
                ".by"),
            ["BZ"] = new(
                "BZ",
                "BLZ",
                "Belize",
                1974,
                ".bz"),
            ["CA"] = new(
                "CA",
                "CAN",
                "Canada",
                1974,
                ".ca"),
            ["CC"] = new(
                "CC",
                "CCK",
                "Cocos (Keeling) Islands",
                1974,
                ".cc"),
            ["CD"] = new(
                "CD",
                "COD",
                "Congo, Democratic Republic of the",
                1997,
                ".cd"),
            ["CF"] = new(
                "CF",
                "CAF",
                "Central African Republic",
                1974,
                ".cf"),
            ["CG"] = new(
                "CG",
                "COG",
                "Congo",
                1974,
                ".cg"),
            ["CH"] = new(
                "CH",
                "CHE",
                "Switzerland",
                1974,
                ".ch"),
            ["CI"] = new(
                "CI",
                "CIV",
                "Côte d'Ivoire",
                1974,
                ".ci"),
            ["CK"] = new(
                "CK",
                "COK",
                "Cook Islands",
                1974,
                ".ck"),
            ["CL"] = new(
                "CL",
                "CHL",
                "Chile",
                1974,
                ".cl"),
            ["CM"] = new(
                "CM",
                "CMR",
                "Cameroon",
                1974,
                ".cm"),
            ["CN"] = new(
                "CN",
                "CHN",
                "China",
                1974,
                ".cn"),
            ["CO"] = new(
                "CO",
                "COL",
                "Colombia",
                1974,
                ".co"),
            ["CR"] = new(
                "CR",
                "CRI",
                "Costa Rica",
                1974,
                ".cr"),
            ["CU"] = new(
                "CU",
                "CUB",
                "Cuba",
                1974,
                ".cu"),
            ["CV"] = new(
                "CV",
                "CPV",
                "Cabo Verde",
                1974,
                ".cv"),
            ["CW"] = new(
                "CW",
                "CUW",
                "Curaçao",
                2010,
                ".cw"),
            ["CX"] = new(
                "CX",
                "CXR",
                "Christmas Island",
                1974,
                ".cx"),
            ["CY"] = new(
                "CY",
                "CYP",
                "Cyprus",
                1974,
                ".cy"),
            ["CZ"] = new(
                "CZ",
                "CZE",
                "Czechia",
                1993,
                ".cz"),
            ["DE"] = new(
                "DE",
                "DEU",
                "Germany",
                1974,
                ".de"),
            ["DJ"] = new(
                "DJ",
                "DJI",
                "Djibouti",
                1977,
                ".dj"),
            ["DK"] = new(
                "DK",
                "DNK",
                "Denmark",
                1974,
                ".dk"),
            ["DM"] = new(
                "DM",
                "DMA",
                "Dominica",
                1974,
                ".dm"),
            ["DO"] = new(
                "DO",
                "DOM",
                "Dominican Republic",
                1974,
                ".do"),
            ["DZ"] = new(
                "DZ",
                "DZA",
                "Algeria",
                1974,
                ".dz"),
            ["EC"] = new(
                "EC",
                "ECU",
                "Ecuador",
                1974,
                ".ec"),
            ["EE"] = new(
                "EE",
                "EST",
                "Estonia",
                1992,
                ".ee"),
            ["EG"] = new(
                "EG",
                "EGY",
                "Egypt",
                1974,
                ".eg"),
            ["EH"] = new(
                "EH",
                "ESH",
                "Western Sahara",
                1974,
                "Previous"),
            ["ER"] = new(
                "ER",
                "ERI",
                "Eritrea",
                1993,
                ".er"),
            ["ES"] = new(
                "ES",
                "ESP",
                "Spain",
                1974,
                ".es"),
            ["ET"] = new(
                "ET",
                "ETH",
                "Ethiopia",
                1974,
                ".et"),
            ["FI"] = new(
                "FI",
                "FIN",
                "Finland",
                1974,
                ".fi"),
            ["FJ"] = new(
                "FJ",
                "FJI",
                "Fiji",
                1974,
                ".fj"),
            ["FK"] = new(
                "FK",
                "FLK",
                "Falkland Islands (Malvinas)",
                1974,
                ".fk"),
            ["FM"] = new(
                "FM",
                "FSM",
                "Micronesia (Federated States of)",
                1986,
                ".fm"),
            ["FO"] = new(
                "FO",
                "FRO",
                "Faroe Islands",
                1974,
                ".fo"),
            ["FR"] = new(
                "FR",
                "FRA",
                "France",
                1974,
                ".fr"),
            ["GA"] = new(
                "GA",
                "GAB",
                "Gabon",
                1974,
                ".ga"),
            ["GB"] = new(
                "GB",
                "GBR",
                "United Kingdom of Great Britain and Northern Ireland",
                1974,
                ".gb"),
            ["GD"] = new(
                "GD",
                "GRD",
                "Grenada",
                1974,
                ".gd"),
            ["GE"] = new(
                "GE",
                "GEO",
                "Georgia",
                1992,
                ".ge"),
            ["GF"] = new(
                "GF",
                "GUF",
                "French Guiana",
                1974,
                ".gf"),
            ["GG"] = new(
                "GG",
                "GGY",
                "Guernsey",
                2006,
                ".gg"),
            ["GH"] = new(
                "GH",
                "GHA",
                "Ghana",
                1974,
                ".gh"),
            ["GI"] = new(
                "GI",
                "GIB",
                "Gibraltar",
                1974,
                ".gi"),
            ["GL"] = new(
                "GL",
                "GRL",
                "Greenland",
                1974,
                ".gl"),
            ["GM"] = new(
                "GM",
                "GMB",
                "Gambia",
                1974,
                ".gm"),
            ["GN"] = new(
                "GN",
                "GIN",
                "Guinea",
                1974,
                ".gn"),
            ["GP"] = new(
                "GP",
                "GLP",
                "Guadeloupe",
                1974,
                ".gp"),
            ["GQ"] = new(
                "GQ",
                "GNQ",
                "Equatorial Guinea",
                1974,
                ".gq"),
            ["GR"] = new(
                "GR",
                "GRC",
                "Greece",
                1974,
                ".gr"),
            ["GS"] = new(
                "GS",
                "SGS",
                "South Georgia and the South Sandwich Islands",
                1993,
                ".gs"),
            ["GT"] = new(
                "GT",
                "GTM",
                "Guatemala",
                1974,
                ".gt"),
            ["GU"] = new(
                "GU",
                "GUM",
                "Guam",
                1974,
                ".gu"),
            ["GW"] = new(
                "GW",
                "GNB",
                "Guinea-Bissau",
                1974,
                ".gw"),
            ["GY"] = new(
                "GY",
                "GUY",
                "Guyana",
                1974,
                ".gy"),
            ["HK"] = new(
                "HK",
                "HKG",
                "Hong Kong",
                1974,
                ".hk"),
            ["HM"] = new(
                "HM",
                "HMD",
                "Heard Island and McDonald Islands",
                1974,
                ".hm"),
            ["HN"] = new(
                "HN",
                "HND",
                "Honduras",
                1974,
                ".hn"),
            ["HR"] = new(
                "HR",
                "HRV",
                "Croatia",
                1992,
                ".hr"),
            ["HT"] = new(
                "HT",
                "HTI",
                "Haiti",
                1974,
                ".ht"),
            ["HU"] = new(
                "HU",
                "HUN",
                "Hungary",
                1974,
                ".hu"),
            ["ID"] = new(
                "ID",
                "IDN",
                "Indonesia",
                1974,
                ".id"),
            ["IE"] = new(
                "IE",
                "IRL",
                "Ireland",
                1974,
                ".ie"),
            ["IL"] = new(
                "IL",
                "ISR",
                "Israel",
                1974,
                ".il"),
            ["IM"] = new(
                "IM",
                "IMN",
                "Isle of Man",
                2006,
                ".im"),
            ["IN"] = new(
                "IN",
                "IND",
                "India",
                1974,
                ".in"),
            ["IO"] = new(
                "IO",
                "IOT",
                "British Indian Ocean Territory",
                1974,
                ".io"),
            ["IQ"] = new(
                "IQ",
                "IRQ",
                "Iraq",
                1974,
                ".iq"),
            ["IR"] = new(
                "IR",
                "IRN",
                "Iran (Islamic Republic of)",
                1974,
                ".ir"),
            ["IS"] = new(
                "IS",
                "ISL",
                "Iceland",
                1974,
                ".is"),
            ["IT"] = new(
                "IT",
                "ITA",
                "Italy",
                1974,
                ".it"),
            ["JE"] = new(
                "JE",
                "JEY",
                "Jersey",
                2006,
                ".je"),
            ["JM"] = new(
                "JM",
                "JAM",
                "Jamaica",
                1974,
                ".jm"),
            ["JO"] = new(
                "JO",
                "JOR",
                "Jordan",
                1974,
                ".jo"),
            ["JP"] = new(
                "JP",
                "JPN",
                "Japan",
                1974,
                ".jp"),
            ["KE"] = new(
                "KE",
                "KEN",
                "Kenya",
                1974,
                ".ke"),
            ["KG"] = new(
                "KG",
                "KGZ",
                "Kyrgyzstan",
                1992,
                ".kg"),
            ["KH"] = new(
                "KH",
                "KHM",
                "Cambodia",
                1974,
                ".kh"),
            ["KI"] = new(
                "KI",
                "KIR",
                "Kiribati",
                1979,
                ".ki"),
            ["KM"] = new(
                "KM",
                "COM",
                "Comoros",
                1974,
                ".km"),
            ["KN"] = new(
                "KN",
                "KNA",
                "Saint Kitts and Nevis",
                1974,
                ".kn"),
            ["KP"] = new(
                "KP",
                "PRK",
                "Korea (Democratic People's Republic of)",
                1974,
                ".kp"),
            ["KR"] = new(
                "KR",
                "KOR",
                "Korea, Republic of",
                1974,
                ".kr"),
            ["KW"] = new(
                "KW",
                "KWT",
                "Kuwait",
                1974,
                ".kw"),
            ["KY"] = new(
                "KY",
                "CYM",
                "Cayman Islands",
                1974,
                ".ky"),
            ["KZ"] = new(
                "KZ",
                "KAZ",
                "Kazakhstan",
                1992,
                ".kz"),
            ["LA"] = new(
                "LA",
                "LAO",
                "Lao People's Democratic Republic",
                1974,
                ".la"),
            ["LB"] = new(
                "LB",
                "LBN",
                "Lebanon",
                1974,
                ".lb"),
            ["LC"] = new(
                "LC",
                "LCA",
                "Saint Lucia",
                1974,
                ".lc"),
            ["LI"] = new(
                "LI",
                "LIE",
                "Liechtenstein",
                1974,
                ".li"),
            ["LK"] = new(
                "LK",
                "LKA",
                "Sri Lanka",
                1974,
                ".lk"),
            ["LR"] = new(
                "LR",
                "LBR",
                "Liberia",
                1974,
                ".lr"),
            ["LS"] = new(
                "LS",
                "LSO",
                "Lesotho",
                1974,
                ".ls"),
            ["LT"] = new(
                "LT",
                "LTU",
                "Lithuania",
                1992,
                ".lt"),
            ["LU"] = new(
                "LU",
                "LUX",
                "Luxembourg",
                1974,
                ".lu"),
            ["LV"] = new(
                "LV",
                "LVA",
                "Latvia",
                1992,
                ".lv"),
            ["LY"] = new(
                "LY",
                "LBY",
                "Libya",
                1974,
                ".ly"),
            ["MA"] = new(
                "MA",
                "MAR",
                "Morocco",
                1974,
                ".ma"),
            ["MC"] = new(
                "MC",
                "MCO",
                "Monaco",
                1974,
                ".mc"),
            ["MD"] = new(
                "MD",
                "MDA",
                "Moldova, Republic of",
                1992,
                ".md"),
            ["ME"] = new(
                "ME",
                "MNE",
                "Montenegro",
                2006,
                ".me"),
            ["MF"] = new(
                "MF",
                "MAF",
                "Saint Martin (French part)",
                2007,
                ".mf"),
            ["MG"] = new(
                "MG",
                "MDG",
                "Madagascar",
                1974,
                ".mg"),
            ["MH"] = new(
                "MH",
                "MHL",
                "Marshall Islands",
                1986,
                ".mh"),
            ["MK"] = new(
                "MK",
                "MKD",
                "North Macedonia",
                1993,
                ".mk"),
            ["ML"] = new(
                "ML",
                "MLI",
                "Mali",
                1974,
                ".ml"),
            ["MM"] = new(
                "MM",
                "MMR",
                "Myanmar",
                1989,
                ".mm"),
            ["MN"] = new(
                "MN",
                "MNG",
                "Mongolia",
                1974,
                ".mn"),
            ["MO"] = new(
                "MO",
                "MAC",
                "Macao",
                1974,
                ".mo"),
            ["MP"] = new(
                "MP",
                "MNP",
                "Northern Mariana Islands",
                1986,
                ".mp"),
            ["MQ"] = new(
                "MQ",
                "MTQ",
                "Martinique",
                1974,
                ".mq"),
            ["MR"] = new(
                "MR",
                "MRT",
                "Mauritania",
                1974,
                ".mr"),
            ["MS"] = new(
                "MS",
                "MSR",
                "Montserrat",
                1974,
                ".ms"),
            ["MT"] = new(
                "MT",
                "MLT",
                "Malta",
                1974,
                ".mt"),
            ["MU"] = new(
                "MU",
                "MUS",
                "Mauritius",
                1974,
                ".mu"),
            ["MV"] = new(
                "MV",
                "MDV",
                "Maldives",
                1974,
                ".mv"),
            ["MW"] = new(
                "MW",
                "MWI",
                "Malawi",
                1974,
                ".mw"),
            ["MX"] = new(
                "MX",
                "MEX",
                "Mexico",
                1974,
                ".mx"),
            ["MY"] = new(
                "MY",
                "MYS",
                "Malaysia",
                1974,
                ".my"),
            ["MZ"] = new(
                "MZ",
                "MOZ",
                "Mozambique",
                1974,
                ".mz"),
            ["NA"] = new(
                "NA",
                "NAM",
                "Namibia",
                1974,
                ".na"),
            ["NC"] = new(
                "NC",
                "NCL",
                "New Caledonia",
                1974,
                ".nc"),
            ["NE"] = new(
                "NE",
                "NER",
                "Niger",
                1974,
                ".ne"),
            ["NF"] = new(
                "NF",
                "NFK",
                "Norfolk Island",
                1974,
                ".nf"),
            ["NG"] = new(
                "NG",
                "NGA",
                "Nigeria",
                1974,
                ".ng"),
            ["NI"] = new(
                "NI",
                "NIC",
                "Nicaragua",
                1974,
                ".ni"),
            ["NL"] = new(
                "NL",
                "NLD",
                "Netherlands",
                1974,
                ".nl"),
            ["NO"] = new(
                "NO",
                "NOR",
                "Norway",
                1974,
                ".no"),
            ["NP"] = new(
                "NP",
                "NPL",
                "Nepal",
                1974,
                ".np"),
            ["NR"] = new(
                "NR",
                "NRU",
                "Nauru",
                1974,
                ".nr"),
            ["NU"] = new(
                "NU",
                "NIU",
                "Niue",
                1974,
                ".nu"),
            ["NZ"] = new(
                "NZ",
                "NZL",
                "New Zealand",
                1974,
                ".nz"),
            ["OM"] = new(
                "OM",
                "OMN",
                "Oman",
                1974,
                ".om"),
            ["PA"] = new(
                "PA",
                "PAN",
                "Panama",
                1974,
                ".pa"),
            ["PE"] = new(
                "PE",
                "PER",
                "Peru",
                1974,
                ".pe"),
            ["PF"] = new(
                "PF",
                "PYF",
                "French Polynesia",
                1974,
                ".pf"),
            ["PG"] = new(
                "PG",
                "PNG",
                "Papua New Guinea",
                1974,
                ".pg"),
            ["PH"] = new(
                "PH",
                "PHL",
                "Philippines",
                1974,
                ".ph"),
            ["PK"] = new(
                "PK",
                "PAK",
                "Pakistan",
                1974,
                ".pk"),
            ["PL"] = new(
                "PL",
                "POL",
                "Poland",
                1974,
                ".pl"),
            ["PM"] = new(
                "PM",
                "SPM",
                "Saint Pierre and Miquelon",
                1974,
                ".pm"),
            ["PN"] = new(
                "PN",
                "PCN",
                "Pitcairn",
                1974,
                ".pn"),
            ["PR"] = new(
                "PR",
                "PRI",
                "Puerto Rico",
                1974,
                ".pr"),
            ["PS"] = new(
                "PS",
                "PSE",
                "Palestine, State of",
                1999,
                ".ps"),
            ["PT"] = new(
                "PT",
                "PRT",
                "Portugal",
                1974,
                ".pt"),
            ["PW"] = new(
                "PW",
                "PLW",
                "Palau",
                1986,
                ".pw"),
            ["PY"] = new(
                "PY",
                "PRY",
                "Paraguay",
                1974,
                ".py"),
            ["QA"] = new(
                "QA",
                "QAT",
                "Qatar",
                1974,
                ".qa"),
            ["RE"] = new(
                "RE",
                "REU",
                "Réunion",
                1974,
                ".re"),
            ["RO"] = new(
                "RO",
                "ROU",
                "Romania",
                1974,
                ".ro"),
            ["RS"] = new(
                "RS",
                "SRB",
                "Serbia",
                2006,
                ".rs"),
            ["RU"] = new(
                "RU",
                "RUS",
                "Russian Federation",
                1992,
                ".ru"),
            ["RW"] = new(
                "RW",
                "RWA",
                "Rwanda",
                1974,
                ".rw"),
            ["SA"] = new(
                "SA",
                "SAU",
                "Saudi Arabia",
                1974,
                ".sa"),
            ["SB"] = new(
                "SB",
                "SLB",
                "Solomon Islands",
                1974,
                ".sb"),
            ["SC"] = new(
                "SC",
                "SYC",
                "Seychelles",
                1974,
                ".sc"),
            ["SD"] = new(
                "SD",
                "SDN",
                "Sudan",
                1974,
                ".sd"),
            ["SE"] = new(
                "SE",
                "SWE",
                "Sweden",
                1974,
                ".se"),
            ["SG"] = new(
                "SG",
                "SGP",
                "Singapore",
                1974,
                ".sg"),
            ["SH"] = new(
                "SH",
                "SHN",
                "Saint Helena, Ascension and Tristan da Cunha",
                1974,
                ".sh"),
            ["SI"] = new(
                "SI",
                "SVN",
                "Slovenia",
                1992,
                ".si"),
            ["SJ"] = new(
                "SJ",
                "SJM",
                "Svalbard and Jan Mayen",
                1974,
                ".sj"),
            ["SK"] = new(
                "SK",
                "SVK",
                "Slovakia",
                1993,
                ".sk"),
            ["SL"] = new(
                "SL",
                "SLE",
                "Sierra Leone",
                1974,
                ".sl"),
            ["SM"] = new(
                "SM",
                "SMR",
                "San Marino",
                1974,
                ".sm"),
            ["SN"] = new(
                "SN",
                "SEN",
                "Senegal",
                1974,
                ".sn"),
            ["SO"] = new(
                "SO",
                "SOM",
                "Somalia",
                1974,
                ".so"),
            ["SR"] = new(
                "SR",
                "SUR",
                "Suriname",
                1974,
                ".sr"),
            ["SS"] = new(
                "SS",
                "SSD",
                "South Sudan",
                2011,
                ".ss"),
            ["ST"] = new(
                "ST",
                "STP",
                "Sao Tome and Principe",
                1974,
                ".st"),
            ["SV"] = new(
                "SV",
                "SLV",
                "El Salvador",
                1974,
                ".sv"),
            ["SX"] = new(
                "SX",
                "SXM",
                "Sint Maarten (Dutch part)",
                2010,
                ".sx"),
            ["SY"] = new(
                "SY",
                "SYR",
                "Syrian Arab Republic",
                1974,
                ".sy"),
            ["SZ"] = new(
                "SZ",
                "SWZ",
                "Eswatini",
                1974,
                ".sz"),
            ["TC"] = new(
                "TC",
                "TCA",
                "Turks and Caicos Islands",
                1974,
                ".tc"),
            ["TD"] = new(
                "TD",
                "TCD",
                "Chad",
                1974,
                ".td"),
            ["TF"] = new(
                "TF",
                "ATF",
                "French Southern Territories",
                1979,
                ".tf"),
            ["TG"] = new(
                "TG",
                "TGO",
                "Togo",
                1974,
                ".tg"),
            ["TH"] = new(
                "TH",
                "THA",
                "Thailand",
                1974,
                ".th"),
            ["TJ"] = new(
                "TJ",
                "TJK",
                "Tajikistan",
                1992,
                ".tj"),
            ["TK"] = new(
                "TK",
                "TKL",
                "Tokelau",
                1974,
                ".tk"),
            ["TL"] = new(
                "TL",
                "TLS",
                "Timor-Leste",
                2002,
                ".tl"),
            ["TM"] = new(
                "TM",
                "TKM",
                "Turkmenistan",
                1992,
                ".tm"),
            ["TN"] = new(
                "TN",
                "TUN",
                "Tunisia",
                1974,
                ".tn"),
            ["TO"] = new(
                "TO",
                "TON",
                "Tonga",
                1974,
                ".to"),
            ["TR"] = new(
                "TR",
                "TUR",
                "Türkiye",
                1974,
                ".tr"),
            ["TT"] = new(
                "TT",
                "TTO",
                "Trinidad and Tobago",
                1974,
                ".tt"),
            ["TV"] = new(
                "TV",
                "TUV",
                "Tuvalu",
                1977,
                ".tv"),
            ["TW"] = new(
                "TW",
                "TWN",
                "Taiwan, Province of China",
                1974,
                ".tw"),
            ["TZ"] = new(
                "TZ",
                "TZA",
                "Tanzania, United Republic of",
                1974,
                ".tz"),
            ["UA"] = new(
                "UA",
                "UKR",
                "Ukraine",
                1974,
                ".ua"),
            ["UG"] = new(
                "UG",
                "UGA",
                "Uganda",
                1974,
                ".ug"),
            ["UM"] = new(
                "UM",
                "UMI",
                "United States Minor Outlying Islands",
                1986,
                string.Empty),
            ["US"] = new(
                "US",
                "USA",
                "United States of America",
                1974,
                ".us"),
            ["UY"] = new(
                "UY",
                "URY",
                "Uruguay",
                1974,
                ".uy"),
            ["UZ"] = new(
                "UZ",
                "UZB",
                "Uzbekistan",
                1992,
                ".uz"),
            ["VA"] = new(
                "VA",
                "VAT",
                "Holy See",
                1974,
                ".va"),
            ["VC"] = new(
                "VC",
                "VCT",
                "Saint Vincent and the Grenadines",
                1974,
                ".vc"),
            ["VE"] = new(
                "VE",
                "VEN",
                "Venezuela (Bolivarian Republic of)",
                1974,
                ".ve"),
            ["VG"] = new(
                "VG",
                "VGB",
                "Virgin Islands (British)",
                1974,
                ".vg"),
            ["VI"] = new(
                "VI",
                "VIR",
                "Virgin Islands (U.S.)",
                1974,
                ".vi"),
            ["VN"] = new(
                "VN",
                "VNM",
                "Viet Nam",
                1974,
                ".vn"),
            ["VU"] = new(
                "VU",
                "VUT",
                "Vanuatu",
                1980,
                ".vu"),
            ["WF"] = new(
                "WF",
                "WLF",
                "Wallis and Futuna",
                1974,
                ".wf"),
            ["WS"] = new(
                "WS",
                "WSM",
                "Samoa",
                1974,
                ".ws"),
            ["YE"] = new(
                "YE",
                "YEM",
                "Yemen",
                1974,
                ".ye"),
            ["YT"] = new(
                "YT",
                "MYT",
                "Mayotte",
                1993,
                ".yt"),
            ["ZA"] = new(
                "ZA",
                "ZAF",
                "South Africa",
                1974,
                ".za"),
            ["ZM"] = new(
                "ZM",
                "ZMB",
                "Zambia",
                1974,
                ".zm"),
            ["ZW"] = new(
                "ZW",
                "ZWE",
                "Zimbabwe",
                1980,
                ".zw")
        });

    /// <summary>
    /// A list of country records, by their ISO-3166-1 alpha-3 codes.
    /// </summary>
    public static readonly Lazy<IReadOnlyDictionary<string, CountryCode>> CountriesByAlpha3 = new(
        () => new ConcurrentDictionary<string, CountryCode>(
            CountriesByAlpha2.Value.ToDictionary(
                p => p.Value.Alpha3Code,
                p => p.Value)));

    /// <summary>
    /// A list of country records, by their international (English) names.
    /// </summary>
    public static readonly Lazy<IReadOnlyDictionary<string, CountryCode>> CountriesByInternationalName = new(
        () => new ConcurrentDictionary<string, CountryCode>(
            CountriesByAlpha2.Value.ToDictionary(
                p => p.Value.Name,
                p => p.Value)));

    /// <summary>
    /// A list of country records, by their top level domains.
    /// </summary>
    public static readonly Lazy<IReadOnlyDictionary<string, CountryCode>> CountriesByTopLevelDomain = new(
        () => new ConcurrentDictionary<string, CountryCode>(
            CountriesByAlpha2.Value.Where(p => !string.IsNullOrWhiteSpace(p.Value.TopLevelDomain)).ToDictionary(
                p => p.Value.TopLevelDomain,
                p => p.Value)));

    /// <summary>
    /// A country code detailed entry.
    /// </summary>
    /// <param name="Alpha2Code">The ISO 1366-1 alpha-2 code for the country.</param>
    /// <param name="Alpha3Code">The ISO 1366-1 alpha-3 code for the country.</param>
    /// <param name="Name">The name of the country or territory.</param>
    /// <param name="YearOfAssignment">The year in which the code was assigned.</param>
    /// <param name="TopLevelDomain">The top-level domain for the country or territory.</param>
    public record CountryCode(
        string Alpha2Code,
        string Alpha3Code,
        string Name,
        int YearOfAssignment,
        string TopLevelDomain);
}