using IX.StandardExtensions.Efficiency;

using JetBrains.Annotations;

namespace IX.StandardExtensions.Globalization;

/// <summary>
/// Country codes.
/// </summary>
[PublicAPI]
public class CountryCodes
{
    /// <summary>
    /// A list of country records, by their ISO-3166-1 alpha-2 codes.
    /// </summary>
    public static ConcurrentDictionary<string, CountryCode> CountriesByAlpha2 =
        new()
        {
            ["AD"] = new(
                "AD",
                "",
                "Andorra",
                1974,
                ".ad"),
            ["AE"] = new(
                "AE",
                "ARE",
                "United Arab Emirates",
                1974,
                ".ae"),
            ["AF"] = new(
                "AF",
                "AFG",
                "Afghanistan",
                1974,
                ".af"),
            ["AG"] = new(
                "AG",
                "ATG",
                "Antigua and Barbuda",
                1974,
                ".ag"),
            ["AI"] = new(
                "AI",
                "AIA",
                "Anguilla",
                1985,
                ".ai"),
            ["AL"] = new(
                "AL",
                "ALB",
                "Albania",
                1974,
                ".al"),
            ["AM"] = new(
                "AM",
                "ARM",
                "Armenia",
                1992,
                ".am"),
            ["AO"] = new(
                "AO",
                "AGO",
                "Angola",
                1974,
                ".ao"),
            ["AQ"] = new(
                "AQ",
                "ATA",
                "Antarctica",
                1974,
                ".aq"),
            ["AR"] = new(
                "AR",
                "ARG",
                "Argentina",
                1974,
                ".ar"),
            ["AS"] = new(
                "AS",
                "ASM",
                "American Samoa",
                1974,
                ".as"),
            ["AT"] = new(
                "AT",
                "AUT",
                "Austria",
                1974,
                ".at"),
            ["AU"] = new(
                "AU",
                "AUS",
                "Australia",
                1974,
                ".au"),
            ["AW"] = new(
                "AW",
                "ABW",
                "Aruba",
                1986,
                ".aw"),
            ["AX"] = new(
                "AX",
                "",
                "Åland Islands",
                2004,
                ".ax"),
            ["AZ"] = new(
                "AZ",
                "AZE",
                "Azerbaijan",
                1992,
                ".az"),
            ["BA"] = new(
                "BA",
                "BIH",
                "Bosnia and Herzegovina",
                1992,
                ".ba"),
            ["BB"] = new(
                "BB",
                "BRB",
                "Barbados",
                1974,
                ".bb"),
            ["BD"] = new(
                "BD",
                "BGD",
                "Bangladesh",
                1974,
                ".bd"),
            ["BE"] = new(
                "BE",
                "BEL",
                "Belgium",
                1974,
                ".be"),
            ["BF"] = new(
                "BF",
                "BFA",
                "Burkina Faso",
                1984,
                ".bf"),
            ["BG"] = new(
                "BG",
                "BGR",
                "Bulgaria",
                1974,
                ".bg"),
            ["BH"] = new(
                "BH",
                "BHR",
                "Bahrain",
                1974,
                ".bh"),
            ["BI"] = new(
                "BI",
                "BDI",
                "Burundi",
                1974,
                ".bi"),
            ["BJ"] = new(
                "BJ",
                "BEN",
                "Benin",
                1977,
                ".bj"),
            ["BL"] = new(
                "BL",
                "BLM",
                "Saint Barthélemy",
                2007,
                ".bl"),
            ["BM"] = new(
                "BM",
                "BMU",
                "Bermuda",
                1974,
                ".bm"),
            ["BN"] = new(
                "BN",
                "BRN",
                "Brunei Darussalam",
                1974,
                ".bn"),
            ["BO"] = new(
                "BO",
                "BOL",
                "Bolivia (Plurinational State of)",
                1974,
                ".bo"),
            ["BQ"] = new(
                "BQ",
                "BES",
                "Bonaire, Sint Eustatius and Saba",
                2010,
                ".bq"),
            ["BR"] = new(
                "BR",
                "BRA",
                "Brazil",
                1974,
                ".br"),
            ["BS"] = new(
                "BS",
                "BHS",
                "Bahamas",
                1974,
                ".bs"),
            ["BT"] = new(
                "BT",
                "BTN",
                "Bhutan",
                1974,
                ".bt"),
            ["BV"] = new(
                "BV",
                "BVT",
                "Bouvet Island",
                1974,
                ".bv"),
            ["BW"] = new(
                "BW",
                "BWA",
                "Botswana",
                1974,
                ".bw"),
            ["BY"] = new(
                "BY",
                "BLR",
                "Belarus",
                1974,
                ".by"),
            ["BZ"] = new(
                "BZ",
                "BLZ",
                "Belize",
                1974,
                ".bz"),
            ["CA"] = new(
                "CA",
                "CAN",
                "Canada",
                1974,
                ".ca"),
            ["CC"] = new(
                "CC",
                "",
                "Cocos (Keeling) Islands",
                1974,
                ".cc"),
            ["CD"] = new(
                "CD",
                "",
                "Congo, Democratic Republic of the",
                1997,
                ".cd"),
            ["CF"] = new(
                "CF",
                "",
                "Central African Republic",
                1974,
                ".cf"),
            ["CG"] = new(
                "CG",
                "",
                "Congo",
                1974,
                ".cg"),
            ["CH"] = new(
                "CH",
                "",
                "Switzerland",
                1974,
                ".ch"),
            ["CI"] = new(
                "CI",
                "",
                "Côte d'Ivoire",
                1974,
                ".ci"),
            ["CK"] = new(
                "CK",
                "",
                "Cook Islands",
                1974,
                ".ck"),
            ["CL"] = new(
                "CL",
                "",
                "Chile",
                1974,
                ".cl"),
            ["CM"] = new(
                "CM",
                "",
                "Cameroon",
                1974,
                ".cm"),
            ["CN"] = new(
                "CN",
                "",
                "China",
                1974,
                ".cn"),
            ["CO"] = new(
                "CO",
                "",
                "Colombia",
                1974,
                ".co"),
            ["CR"] = new(
                "CR",
                "",
                "Costa Rica",
                1974,
                ".cr"),
            ["CU"] = new(
                "CU",
                "",
                "Cuba",
                1974,
                ".cu"),
            ["CV"] = new(
                "CV",
                "",
                "Cabo Verde",
                1974,
                ".cv"),
            ["CW"] = new(
                "CW",
                "",
                "Curaçao",
                2010,
                ".cw"),
            ["CX"] = new(
                "CX",
                "",
                "Christmas Island",
                1974,
                ".cx"),
            ["CY"] = new(
                "CY",
                "",
                "Cyprus",
                1974,
                ".cy"),
            ["CZ"] = new(
                "CZ",
                "",
                "Czechia",
                1993,
                ".cz"),
            ["DE"] = new(
                "DE",
                "",
                "Germany",
                1974,
                ".de"),
            ["DJ"] = new(
                "DJ",
                "",
                "Djibouti",
                1977,
                ".dj"),
            ["DK"] = new(
                "DK",
                "",
                "Denmark",
                1974,
                ".dk"),
            ["DM"] = new(
                "DM",
                "",
                "Dominica",
                1974,
                ".dm"),
            ["DO"] = new(
                "DO",
                "",
                "Dominican Republic",
                1974,
                ".do"),
            ["DZ"] = new(
                "DZ",
                "",
                "Algeria",
                1974,
                ".dz"),
            ["EC"] = new(
                "EC",
                "",
                "Ecuador",
                1974,
                ".ec"),
            ["EE"] = new(
                "EE",
                "",
                "Estonia",
                1992,
                ".ee"),
            ["EG"] = new(
                "EG",
                "",
                "Egypt",
                1974,
                ".eg"),
            ["EH"] = new(
                "EH",
                "",
                "Western Sahara",
                1974,
                "Previous"),
            ["ER"] = new(
                "ER",
                "",
                "Eritrea",
                1993,
                ".er"),
            ["ES"] = new(
                "ES",
                "",
                "Spain",
                1974,
                ".es"),
            ["ET"] = new(
                "ET",
                "",
                "Ethiopia",
                1974,
                ".et"),
            ["FI"] = new(
                "FI",
                "",
                "Finland",
                1974,
                ".fi"),
            ["FJ"] = new(
                "FJ",
                "",
                "Fiji",
                1974,
                ".fj"),
            ["FK"] = new(
                "FK",
                "",
                "Falkland Islands (Malvinas)",
                1974,
                ".fk"),
            ["FM"] = new(
                "FM",
                "",
                "Micronesia (Federated States of)",
                1986,
                ".fm"),
            ["FO"] = new(
                "FO",
                "",
                "Faroe Islands",
                1974,
                ".fo"),
            ["FR"] = new(
                "FR",
                "",
                "France",
                1974,
                ".fr"),
            ["GA"] = new(
                "GA",
                "",
                "Gabon",
                1974,
                ".ga"),
            ["GB"] = new(
                "GB",
                "",
                "United Kingdom of Great Britain and Northern Ireland",
                1974,
                ".gb"),
            ["GD"] = new(
                "GD",
                "",
                "Grenada",
                1974,
                ".gd"),
            ["GE"] = new(
                "GE",
                "",
                "Georgia",
                1992,
                ".ge"),
            ["GF"] = new(
                "GF",
                "",
                "French Guiana",
                1974,
                ".gf"),
            ["GG"] = new(
                "GG",
                "",
                "Guernsey",
                2006,
                ".gg"),
            ["GH"] = new(
                "GH",
                "",
                "Ghana",
                1974,
                ".gh"),
            ["GI"] = new(
                "GI",
                "",
                "Gibraltar",
                1974,
                ".gi"),
            ["GL"] = new(
                "GL",
                "",
                "Greenland",
                1974,
                ".gl"),
            ["GM"] = new(
                "GM",
                "",
                "Gambia",
                1974,
                ".gm"),
            ["GN"] = new(
                "GN",
                "",
                "Guinea",
                1974,
                ".gn"),
            ["GP"] = new(
                "GP",
                "",
                "Guadeloupe",
                1974,
                ".gp"),
            ["GQ"] = new(
                "GQ",
                "",
                "Equatorial Guinea",
                1974,
                ".gq"),
            ["GR"] = new(
                "GR",
                "",
                "Greece",
                1974,
                ".gr"),
            ["GS"] = new(
                "GS",
                "",
                "South Georgia and the South Sandwich Islands",
                1993,
                ".gs"),
            ["GT"] = new(
                "GT",
                "",
                "Guatemala",
                1974,
                ".gt"),
            ["GU"] = new(
                "GU",
                "",
                "Guam",
                1974,
                ".gu"),
            ["GW"] = new(
                "GW",
                "",
                "Guinea-Bissau",
                1974,
                ".gw"),
            ["GY"] = new(
                "GY",
                "",
                "Guyana",
                1974,
                ".gy"),
            ["HK"] = new(
                "HK",
                "",
                "Hong Kong",
                1974,
                ".hk"),
            ["HM"] = new(
                "HM",
                "",
                "Heard Island and McDonald Islands",
                1974,
                ".hm"),
            ["HN"] = new(
                "HN",
                "",
                "Honduras",
                1974,
                ".hn"),
            ["HR"] = new(
                "HR",
                "",
                "Croatia",
                1992,
                ".hr"),
            ["HT"] = new(
                "HT",
                "",
                "Haiti",
                1974,
                ".ht"),
            ["HU"] = new(
                "HU",
                "",
                "Hungary",
                1974,
                ".hu"),
            ["ID"] = new(
                "ID",
                "",
                "Indonesia",
                1974,
                ".id"),
            ["IE"] = new(
                "IE",
                "",
                "Ireland",
                1974,
                ".ie"),
            ["IL"] = new(
                "IL",
                "",
                "Israel",
                1974,
                ".il"),
            ["IM"] = new(
                "IM",
                "",
                "Isle of Man",
                2006,
                ".im"),
            ["IN"] = new(
                "IN",
                "",
                "India",
                1974,
                ".in"),
            ["IO"] = new(
                "IO",
                "",
                "British Indian Ocean Territory",
                1974,
                ".io"),
            ["IQ"] = new(
                "IQ",
                "",
                "Iraq",
                1974,
                ".iq"),
            ["IR"] = new(
                "IR",
                "",
                "Iran (Islamic Republic of)",
                1974,
                ".ir"),
            ["IS"] = new(
                "IS",
                "",
                "Iceland",
                1974,
                ".is"),
            ["IT"] = new(
                "IT",
                "",
                "Italy",
                1974,
                ".it"),
            ["JE"] = new(
                "JE",
                "",
                "Jersey",
                2006,
                ".je"),
            ["JM"] = new(
                "JM",
                "",
                "Jamaica",
                1974,
                ".jm"),
            ["JO"] = new(
                "JO",
                "",
                "Jordan",
                1974,
                ".jo"),
            ["JP"] = new(
                "JP",
                "",
                "Japan",
                1974,
                ".jp"),
            ["KE"] = new(
                "KE",
                "",
                "Kenya",
                1974,
                ".ke"),
            ["KG"] = new(
                "KG",
                "",
                "Kyrgyzstan",
                1992,
                ".kg"),
            ["KH"] = new(
                "KH",
                "",
                "Cambodia",
                1974,
                ".kh"),
            ["KI"] = new(
                "KI",
                "",
                "Kiribati",
                1979,
                ".ki"),
            ["KM"] = new(
                "KM",
                "",
                "Comoros",
                1974,
                ".km"),
            ["KN"] = new(
                "KN",
                "",
                "Saint Kitts and Nevis",
                1974,
                ".kn"),
            ["KP"] = new(
                "KP",
                "",
                "Korea (Democratic People's Republic of)",
                1974,
                ".kp"),
            ["KR"] = new(
                "KR",
                "",
                "Korea, Republic of",
                1974,
                ".kr"),
            ["KW"] = new(
                "KW",
                "",
                "Kuwait",
                1974,
                ".kw"),
            ["KY"] = new(
                "KY",
                "",
                "Cayman Islands",
                1974,
                ".ky"),
            ["KZ"] = new(
                "KZ",
                "",
                "Kazakhstan",
                1992,
                ".kz"),
            ["LA"] = new(
                "LA",
                "",
                "Lao People's Democratic Republic",
                1974,
                ".la"),
            ["LB"] = new(
                "LB",
                "",
                "Lebanon",
                1974,
                ".lb"),
            ["LC"] = new(
                "LC",
                "",
                "Saint Lucia",
                1974,
                ".lc"),
            ["LI"] = new(
                "LI",
                "",
                "Liechtenstein",
                1974,
                ".li"),
            ["LK"] = new(
                "LK",
                "",
                "Sri Lanka",
                1974,
                ".lk"),
            ["LR"] = new(
                "LR",
                "",
                "Liberia",
                1974,
                ".lr"),
            ["LS"] = new(
                "LS",
                "",
                "Lesotho",
                1974,
                ".ls"),
            ["LT"] = new(
                "LT",
                "",
                "Lithuania",
                1992,
                ".lt"),
            ["LU"] = new(
                "LU",
                "",
                "Luxembourg",
                1974,
                ".lu"),
            ["LV"] = new(
                "LV",
                "",
                "Latvia",
                1992,
                ".lv"),
            ["LY"] = new(
                "LY",
                "",
                "Libya",
                1974,
                ".ly"),
            ["MA"] = new(
                "MA",
                "",
                "Morocco",
                1974,
                ".ma"),
            ["MC"] = new(
                "MC",
                "",
                "Monaco",
                1974,
                ".mc"),
            ["MD"] = new(
                "MD",
                "",
                "Moldova, Republic of",
                1992,
                ".md"),
            ["ME"] = new(
                "ME",
                "",
                "Montenegro",
                2006,
                ".me"),
            ["MF"] = new(
                "MF",
                "",
                "Saint Martin (French part)",
                2007,
                ".mf"),
            ["MG"] = new(
                "MG",
                "",
                "Madagascar",
                1974,
                ".mg"),
            ["MH"] = new(
                "MH",
                "",
                "Marshall Islands",
                1986,
                ".mh"),
            ["MK"] = new(
                "MK",
                "",
                "North Macedonia",
                1993,
                ".mk"),
            ["ML"] = new(
                "ML",
                "",
                "Mali",
                1974,
                ".ml"),
            ["MM"] = new(
                "MM",
                "",
                "Myanmar",
                1989,
                ".mm"),
            ["MN"] = new(
                "MN",
                "",
                "Mongolia",
                1974,
                ".mn"),
            ["MO"] = new(
                "MO",
                "",
                "Macao",
                1974,
                ".mo"),
            ["MP"] = new(
                "MP",
                "",
                "Northern Mariana Islands",
                1986,
                ".mp"),
            ["MQ"] = new(
                "MQ",
                "",
                "Martinique",
                1974,
                ".mq"),
            ["MR"] = new(
                "MR",
                "",
                "Mauritania",
                1974,
                ".mr"),
            ["MS"] = new(
                "MS",
                "",
                "Montserrat",
                1974,
                ".ms"),
            ["MT"] = new(
                "MT",
                "",
                "Malta",
                1974,
                ".mt"),
            ["MU"] = new(
                "MU",
                "",
                "Mauritius",
                1974,
                ".mu"),
            ["MV"] = new(
                "MV",
                "",
                "Maldives",
                1974,
                ".mv"),
            ["MW"] = new(
                "MW",
                "",
                "Malawi",
                1974,
                ".mw"),
            ["MX"] = new(
                "MX",
                "",
                "Mexico",
                1974,
                ".mx"),
            ["MY"] = new(
                "MY",
                "",
                "Malaysia",
                1974,
                ".my"),
            ["MZ"] = new(
                "MZ",
                "",
                "Mozambique",
                1974,
                ".mz"),
            ["NA"] = new(
                "NA",
                "",
                "Namibia",
                1974,
                ".na"),
            ["NC"] = new(
                "NC",
                "",
                "New Caledonia",
                1974,
                ".nc"),
            ["NE"] = new(
                "NE",
                "",
                "Niger",
                1974,
                ".ne"),
            ["NF"] = new(
                "NF",
                "",
                "Norfolk Island",
                1974,
                ".nf"),
            ["NG"] = new(
                "NG",
                "",
                "Nigeria",
                1974,
                ".ng"),
            ["NI"] = new(
                "NI",
                "",
                "Nicaragua",
                1974,
                ".ni"),
            ["NL"] = new(
                "NL",
                "",
                "Netherlands",
                1974,
                ".nl"),
            ["NO"] = new(
                "NO",
                "",
                "Norway",
                1974,
                ".no"),
            ["NP"] = new(
                "NP",
                "",
                "Nepal",
                1974,
                ".np"),
            ["NR"] = new(
                "NR",
                "",
                "Nauru",
                1974,
                ".nr"),
            ["NU"] = new(
                "NU",
                "",
                "Niue",
                1974,
                ".nu"),
            ["NZ"] = new(
                "NZ",
                "",
                "New Zealand",
                1974,
                ".nz"),
            ["OM"] = new(
                "OM",
                "",
                "Oman",
                1974,
                ".om"),
            ["PA"] = new(
                "PA",
                "",
                "Panama",
                1974,
                ".pa"),
            ["PE"] = new(
                "PE",
                "",
                "Peru",
                1974,
                ".pe"),
            ["PF"] = new(
                "PF",
                "",
                "French Polynesia",
                1974,
                ".pf"),
            ["PG"] = new(
                "PG",
                "",
                "Papua New Guinea",
                1974,
                ".pg"),
            ["PH"] = new(
                "PH",
                "",
                "Philippines",
                1974,
                ".ph"),
            ["PK"] = new(
                "PK",
                "",
                "Pakistan",
                1974,
                ".pk"),
            ["PL"] = new(
                "PL",
                "",
                "Poland",
                1974,
                ".pl"),
            ["PM"] = new(
                "PM",
                "",
                "Saint Pierre and Miquelon",
                1974,
                ".pm"),
            ["PN"] = new(
                "PN",
                "",
                "Pitcairn",
                1974,
                ".pn"),
            ["PR"] = new(
                "PR",
                "",
                "Puerto Rico",
                1974,
                ".pr"),
            ["PS"] = new(
                "PS",
                "",
                "Palestine, State of",
                1999,
                ".ps"),
            ["PT"] = new(
                "PT",
                "",
                "Portugal",
                1974,
                ".pt"),
            ["PW"] = new(
                "PW",
                "",
                "Palau",
                1986,
                ".pw"),
            ["PY"] = new(
                "PY",
                "",
                "Paraguay",
                1974,
                ".py"),
            ["QA"] = new(
                "QA",
                "",
                "Qatar",
                1974,
                ".qa"),
            ["RE"] = new(
                "RE",
                "",
                "Réunion",
                1974,
                ".re"),
            ["RO"] = new(
                "RO",
                "",
                "Romania",
                1974,
                ".ro"),
            ["RS"] = new(
                "RS",
                "",
                "Serbia",
                2006,
                ".rs"),
            ["RU"] = new(
                "RU",
                "",
                "Russian Federation",
                1992,
                ".ru"),
            ["RW"] = new(
                "RW",
                "",
                "Rwanda",
                1974,
                ".rw"),
            ["SA"] = new(
                "SA",
                "",
                "Saudi Arabia",
                1974,
                ".sa"),
            ["SB"] = new(
                "SB",
                "",
                "Solomon Islands",
                1974,
                ".sb"),
            ["SC"] = new(
                "SC",
                "",
                "Seychelles",
                1974,
                ".sc"),
            ["SD"] = new(
                "SD",
                "",
                "Sudan",
                1974,
                ".sd"),
            ["SE"] = new(
                "SE",
                "",
                "Sweden",
                1974,
                ".se"),
            ["SG"] = new(
                "SG",
                "",
                "Singapore",
                1974,
                ".sg"),
            ["SH"] = new(
                "SH",
                "",
                "Saint Helena, Ascension and Tristan da Cunha",
                1974,
                ".sh"),
            ["SI"] = new(
                "SI",
                "",
                "Slovenia",
                1992,
                ".si"),
            ["SJ"] = new(
                "SJ",
                "",
                "Svalbard and Jan Mayen",
                1974,
                ".sj"),
            ["SK"] = new(
                "SK",
                "",
                "Slovakia",
                1993,
                ".sk"),
            ["SL"] = new(
                "SL",
                "",
                "Sierra Leone",
                1974,
                ".sl"),
            ["SM"] = new(
                "SM",
                "",
                "San Marino",
                1974,
                ".sm"),
            ["SN"] = new(
                "SN",
                "",
                "Senegal",
                1974,
                ".sn"),
            ["SO"] = new(
                "SO",
                "",
                "Somalia",
                1974,
                ".so"),
            ["SR"] = new(
                "SR",
                "",
                "Suriname",
                1974,
                ".sr"),
            ["SS"] = new(
                "SS",
                "",
                "South Sudan",
                2011,
                ".ss"),
            ["ST"] = new(
                "ST",
                "",
                "Sao Tome and Principe",
                1974,
                ".st"),
            ["SV"] = new(
                "SV",
                "",
                "El Salvador",
                1974,
                ".sv"),
            ["SX"] = new(
                "SX",
                "",
                "Sint Maarten (Dutch part)",
                2010,
                ".sx"),
            ["SY"] = new(
                "SY",
                "",
                "Syrian Arab Republic",
                1974,
                ".sy"),
            ["SZ"] = new(
                "SZ",
                "",
                "Eswatini",
                1974,
                ".sz"),
            ["TC"] = new(
                "TC",
                "",
                "Turks and Caicos Islands",
                1974,
                ".tc"),
            ["TD"] = new(
                "TD",
                "",
                "Chad",
                1974,
                ".td"),
            ["TF"] = new(
                "TF",
                "",
                "French Southern Territories",
                1979,
                ".tf"),
            ["TG"] = new(
                "TG",
                "",
                "Togo",
                1974,
                ".tg"),
            ["TH"] = new(
                "TH",
                "",
                "Thailand",
                1974,
                ".th"),
            ["TJ"] = new(
                "TJ",
                "",
                "Tajikistan",
                1992,
                ".tj"),
            ["TK"] = new(
                "TK",
                "",
                "Tokelau",
                1974,
                ".tk"),
            ["TL"] = new(
                "TL",
                "",
                "Timor-Leste",
                2002,
                ".tl"),
            ["TM"] = new(
                "TM",
                "",
                "Turkmenistan",
                1992,
                ".tm"),
            ["TN"] = new(
                "TN",
                "",
                "Tunisia",
                1974,
                ".tn"),
            ["TO"] = new(
                "TO",
                "",
                "Tonga",
                1974,
                ".to"),
            ["TR"] = new(
                "TR",
                "",
                "Türkiye",
                1974,
                ".tr"),
            ["TT"] = new(
                "TT",
                "",
                "Trinidad and Tobago",
                1974,
                ".tt"),
            ["TV"] = new(
                "TV",
                "",
                "Tuvalu",
                1977,
                ".tv"),
            ["TW"] = new(
                "TW",
                "",
                "Taiwan, Province of China",
                1974,
                ".tw"),
            ["TZ"] = new(
                "TZ",
                "",
                "Tanzania, United Republic of",
                1974,
                ".tz"),
            ["UA"] = new(
                "UA",
                "",
                "Ukraine",
                1974,
                ".ua"),
            ["UG"] = new(
                "UG",
                "",
                "Uganda",
                1974,
                ".ug"),
            ["UM"] = new(
                "UM",
                "",
                "United States Minor Outlying Islands",
                1986,
                "Consists"),

            ["US"] = new(
                "US",
                "",
                "United States of America",
                1974,
                ".us"),
            ["UY"] = new(
                "UY",
                "",
                "Uruguay",
                1974,
                ".uy"),
            ["UZ"] = new(
                "UZ",
                "",
                "Uzbekistan",
                1992,
                ".uz"),
            ["VA"] = new(
                "VA",
                "",
                "Holy See",
                1974,
                ".va"),
            ["VC"] = new(
                "VC",
                "",
                "Saint Vincent and the Grenadines",
                1974,
                ".vc"),
            ["VE"] = new(
                "VE",
                "",
                "Venezuela (Bolivarian Republic of)",
                1974,
                ".ve"),
            ["VG"] = new(
                "VG",
                "",
                "Virgin Islands (British)",
                1974,
                ".vg"),
            ["VI"] = new(
                "VI",
                "",
                "Virgin Islands (U.S.)",
                1974,
                ".vi"),
            ["VN"] = new(
                "VN",
                "",
                "Viet Nam",
                1974,
                ".vn"),
            ["VU"] = new(
                "VU",
                "",
                "Vanuatu",
                1980,
                ".vu"),
            ["WF"] = new(
                "WF",
                "",
                "Wallis and Futuna",
                1974,
                ".wf"),
            ["WS"] = new(
                "WS",
                "",
                "Samoa",
                1974,
                ".ws"),
            ["YE"] = new(
                "YE",
                "",
                "Yemen",
                1974,
                ".ye"),
            ["YT"] = new(
                "YT",
                "",
                "Mayotte",
                1993,
                ".yt"),
            ["ZA"] = new(
                "ZA",
                "",
                "South Africa",
                1974,
                ".za"),
            ["ZM"] = new(
                "ZM",
                "",
                "Zambia",
                1974,
                ".zm"),
            ["ZW"] = new(
                "ZW",
                "",
                "Zimbabwe",
                1980,
                "")

        };

/// <summary>
/// A country code detailed entry.
/// </summary>
/// <param name="Alpha2Code">The ISO 1366-1 alpha-2 code for the country.</param>
/// <param name="Alpha3Code">The ISO 1366-1 alpha-3 code for the country.</param>
/// <param name="Name">The name of the country or territory.</param>
/// <param name="YearOfAssignment">The year in which the code was assigned.</param>
/// <param name="TopLevelDomain">The top-level domain for the country or territory.</param>
public record CountryCode(
    string Alpha2Code,
    string Alpha3Code,
    string Name,
    int YearOfAssignment,
    string TopLevelDomain);
}